version: '3.8'

services:
  postgres:
    image: postgres:13.3
    env_file:
      - postgres.env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "./data/pgdata:/var/lib/postgresql/data/pgdata"
      - "./data/restore_from:/docker-entrypoint-initdb.d"

  python:
    build:
      context: ./python
    env_file:
      - postgres.env
    depends_on:
      - postgres
    volumes:
      - "./python/code:/app"
